#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateNextYear
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UFSystem")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertUA_Account_sub(UA_Account_sub instance);
    partial void UpdateUA_Account_sub(UA_Account_sub instance);
    partial void DeleteUA_Account_sub(UA_Account_sub instance);
    partial void InsertUA_Account(UA_Account instance);
    partial void UpdateUA_Account(UA_Account instance);
    partial void DeleteUA_Account(UA_Account instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::CreateNextYear.Properties.Settings.Default.UFSystemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UA_Account_sub> UA_Account_sub
		{
			get
			{
				return this.GetTable<UA_Account_sub>();
			}
		}
		
		public System.Data.Linq.Table<UA_Account> UA_Account
		{
			get
			{
				return this.GetTable<UA_Account>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UA_Account_sub")]
	public partial class UA_Account_sub : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cAcc_Id;
		
		private short _iYear;
		
		private string _cSub_Id;
		
		private bool _bIsDelete;
		
		private System.Nullable<bool> _bClosing;
		
		private System.Nullable<byte> _iModiPeri;
		
		private System.Nullable<System.DateTime> _dSubSysUsed;
		
		private EntityRef<UA_Account> _UA_Account;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncAcc_IdChanging(string value);
    partial void OncAcc_IdChanged();
    partial void OniYearChanging(short value);
    partial void OniYearChanged();
    partial void OncSub_IdChanging(string value);
    partial void OncSub_IdChanged();
    partial void OnbIsDeleteChanging(bool value);
    partial void OnbIsDeleteChanged();
    partial void OnbClosingChanging(System.Nullable<bool> value);
    partial void OnbClosingChanged();
    partial void OniModiPeriChanging(System.Nullable<byte> value);
    partial void OniModiPeriChanged();
    partial void OndSubSysUsedChanging(System.Nullable<System.DateTime> value);
    partial void OndSubSysUsedChanged();
    #endregion
		
		public UA_Account_sub()
		{
			this._UA_Account = default(EntityRef<UA_Account>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cAcc_Id", DbType="VarChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cAcc_Id
		{
			get
			{
				return this._cAcc_Id;
			}
			set
			{
				if ((this._cAcc_Id != value))
				{
					if (this._UA_Account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncAcc_IdChanging(value);
					this.SendPropertyChanging();
					this._cAcc_Id = value;
					this.SendPropertyChanged("cAcc_Id");
					this.OncAcc_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iYear", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short iYear
		{
			get
			{
				return this._iYear;
			}
			set
			{
				if ((this._iYear != value))
				{
					this.OniYearChanging(value);
					this.SendPropertyChanging();
					this._iYear = value;
					this.SendPropertyChanged("iYear");
					this.OniYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cSub_Id", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cSub_Id
		{
			get
			{
				return this._cSub_Id;
			}
			set
			{
				if ((this._cSub_Id != value))
				{
					this.OncSub_IdChanging(value);
					this.SendPropertyChanging();
					this._cSub_Id = value;
					this.SendPropertyChanged("cSub_Id");
					this.OncSub_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bIsDelete", DbType="Bit NOT NULL")]
		public bool bIsDelete
		{
			get
			{
				return this._bIsDelete;
			}
			set
			{
				if ((this._bIsDelete != value))
				{
					this.OnbIsDeleteChanging(value);
					this.SendPropertyChanging();
					this._bIsDelete = value;
					this.SendPropertyChanged("bIsDelete");
					this.OnbIsDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bClosing", DbType="Bit")]
		public System.Nullable<bool> bClosing
		{
			get
			{
				return this._bClosing;
			}
			set
			{
				if ((this._bClosing != value))
				{
					this.OnbClosingChanging(value);
					this.SendPropertyChanging();
					this._bClosing = value;
					this.SendPropertyChanged("bClosing");
					this.OnbClosingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iModiPeri", DbType="TinyInt")]
		public System.Nullable<byte> iModiPeri
		{
			get
			{
				return this._iModiPeri;
			}
			set
			{
				if ((this._iModiPeri != value))
				{
					this.OniModiPeriChanging(value);
					this.SendPropertyChanging();
					this._iModiPeri = value;
					this.SendPropertyChanged("iModiPeri");
					this.OniModiPeriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dSubSysUsed", DbType="DateTime")]
		public System.Nullable<System.DateTime> dSubSysUsed
		{
			get
			{
				return this._dSubSysUsed;
			}
			set
			{
				if ((this._dSubSysUsed != value))
				{
					this.OndSubSysUsedChanging(value);
					this.SendPropertyChanging();
					this._dSubSysUsed = value;
					this.SendPropertyChanged("dSubSysUsed");
					this.OndSubSysUsedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UA_Account_UA_Account_sub", Storage="_UA_Account", ThisKey="cAcc_Id", OtherKey="cAcc_Id", IsForeignKey=true)]
		public UA_Account UA_Account
		{
			get
			{
				return this._UA_Account.Entity;
			}
			set
			{
				UA_Account previousValue = this._UA_Account.Entity;
				if (((previousValue != value) 
							|| (this._UA_Account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UA_Account.Entity = null;
						previousValue.UA_Account_sub.Remove(this);
					}
					this._UA_Account.Entity = value;
					if ((value != null))
					{
						value.UA_Account_sub.Add(this);
						this._cAcc_Id = value.cAcc_Id;
					}
					else
					{
						this._cAcc_Id = default(string);
					}
					this.SendPropertyChanged("UA_Account");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UA_Account")]
	public partial class UA_Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _iSysID;
		
		private string _cAcc_Id;
		
		private string _cAcc_Name;
		
		private string _cAcc_Path;
		
		private short _iYear;
		
		private short _iMonth;
		
		private string _cAcc_Master;
		
		private string _cCurCode;
		
		private string _cCurName;
		
		private string _cUnitName;
		
		private string _cUnitAbbre;
		
		private string _cUnitAddr;
		
		private string _cUnitZap;
		
		private string _cUnitTel;
		
		private string _cUnitFax;
		
		private string _cUnitEMail;
		
		private string _cUnitTaxNo;
		
		private string _cUnitLP;
		
		private string _cFinKind;
		
		private string _cFinType;
		
		private string _cEntType;
		
		private string _cTradeKind;
		
		private EntitySet<UA_Account_sub> _UA_Account_sub;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniSysIDChanging(string value);
    partial void OniSysIDChanged();
    partial void OncAcc_IdChanging(string value);
    partial void OncAcc_IdChanged();
    partial void OncAcc_NameChanging(string value);
    partial void OncAcc_NameChanged();
    partial void OncAcc_PathChanging(string value);
    partial void OncAcc_PathChanged();
    partial void OniYearChanging(short value);
    partial void OniYearChanged();
    partial void OniMonthChanging(short value);
    partial void OniMonthChanged();
    partial void OncAcc_MasterChanging(string value);
    partial void OncAcc_MasterChanged();
    partial void OncCurCodeChanging(string value);
    partial void OncCurCodeChanged();
    partial void OncCurNameChanging(string value);
    partial void OncCurNameChanged();
    partial void OncUnitNameChanging(string value);
    partial void OncUnitNameChanged();
    partial void OncUnitAbbreChanging(string value);
    partial void OncUnitAbbreChanged();
    partial void OncUnitAddrChanging(string value);
    partial void OncUnitAddrChanged();
    partial void OncUnitZapChanging(string value);
    partial void OncUnitZapChanged();
    partial void OncUnitTelChanging(string value);
    partial void OncUnitTelChanged();
    partial void OncUnitFaxChanging(string value);
    partial void OncUnitFaxChanged();
    partial void OncUnitEMailChanging(string value);
    partial void OncUnitEMailChanged();
    partial void OncUnitTaxNoChanging(string value);
    partial void OncUnitTaxNoChanged();
    partial void OncUnitLPChanging(string value);
    partial void OncUnitLPChanged();
    partial void OncFinKindChanging(string value);
    partial void OncFinKindChanged();
    partial void OncFinTypeChanging(string value);
    partial void OncFinTypeChanged();
    partial void OncEntTypeChanging(string value);
    partial void OncEntTypeChanged();
    partial void OncTradeKindChanging(string value);
    partial void OncTradeKindChanged();
    #endregion
		
		public UA_Account()
		{
			this._UA_Account_sub = new EntitySet<UA_Account_sub>(new Action<UA_Account_sub>(this.attach_UA_Account_sub), new Action<UA_Account_sub>(this.detach_UA_Account_sub));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iSysID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string iSysID
		{
			get
			{
				return this._iSysID;
			}
			set
			{
				if ((this._iSysID != value))
				{
					this.OniSysIDChanging(value);
					this.SendPropertyChanging();
					this._iSysID = value;
					this.SendPropertyChanged("iSysID");
					this.OniSysIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cAcc_Id", DbType="VarChar(3) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cAcc_Id
		{
			get
			{
				return this._cAcc_Id;
			}
			set
			{
				if ((this._cAcc_Id != value))
				{
					this.OncAcc_IdChanging(value);
					this.SendPropertyChanging();
					this._cAcc_Id = value;
					this.SendPropertyChanged("cAcc_Id");
					this.OncAcc_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cAcc_Name", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string cAcc_Name
		{
			get
			{
				return this._cAcc_Name;
			}
			set
			{
				if ((this._cAcc_Name != value))
				{
					this.OncAcc_NameChanging(value);
					this.SendPropertyChanging();
					this._cAcc_Name = value;
					this.SendPropertyChanged("cAcc_Name");
					this.OncAcc_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cAcc_Path", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string cAcc_Path
		{
			get
			{
				return this._cAcc_Path;
			}
			set
			{
				if ((this._cAcc_Path != value))
				{
					this.OncAcc_PathChanging(value);
					this.SendPropertyChanging();
					this._cAcc_Path = value;
					this.SendPropertyChanged("cAcc_Path");
					this.OncAcc_PathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iYear", DbType="SmallInt NOT NULL")]
		public short iYear
		{
			get
			{
				return this._iYear;
			}
			set
			{
				if ((this._iYear != value))
				{
					this.OniYearChanging(value);
					this.SendPropertyChanging();
					this._iYear = value;
					this.SendPropertyChanged("iYear");
					this.OniYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iMonth", DbType="SmallInt NOT NULL")]
		public short iMonth
		{
			get
			{
				return this._iMonth;
			}
			set
			{
				if ((this._iMonth != value))
				{
					this.OniMonthChanging(value);
					this.SendPropertyChanging();
					this._iMonth = value;
					this.SendPropertyChanged("iMonth");
					this.OniMonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cAcc_Master", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string cAcc_Master
		{
			get
			{
				return this._cAcc_Master;
			}
			set
			{
				if ((this._cAcc_Master != value))
				{
					this.OncAcc_MasterChanging(value);
					this.SendPropertyChanging();
					this._cAcc_Master = value;
					this.SendPropertyChanged("cAcc_Master");
					this.OncAcc_MasterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCurCode", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string cCurCode
		{
			get
			{
				return this._cCurCode;
			}
			set
			{
				if ((this._cCurCode != value))
				{
					this.OncCurCodeChanging(value);
					this.SendPropertyChanging();
					this._cCurCode = value;
					this.SendPropertyChanged("cCurCode");
					this.OncCurCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cCurName", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string cCurName
		{
			get
			{
				return this._cCurName;
			}
			set
			{
				if ((this._cCurName != value))
				{
					this.OncCurNameChanging(value);
					this.SendPropertyChanging();
					this._cCurName = value;
					this.SendPropertyChanged("cCurName");
					this.OncCurNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cUnitName", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string cUnitName
		{
			get
			{
				return this._cUnitName;
			}
			set
			{
				if ((this._cUnitName != value))
				{
					this.OncUnitNameChanging(value);
					this.SendPropertyChanging();
					this._cUnitName = value;
					this.SendPropertyChanged("cUnitName");
					this.OncUnitNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cUnitAbbre", DbType="VarChar(40)")]
		public string cUnitAbbre
		{
			get
			{
				return this._cUnitAbbre;
			}
			set
			{
				if ((this._cUnitAbbre != value))
				{
					this.OncUnitAbbreChanging(value);
					this.SendPropertyChanging();
					this._cUnitAbbre = value;
					this.SendPropertyChanged("cUnitAbbre");
					this.OncUnitAbbreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cUnitAddr", DbType="VarChar(80)")]
		public string cUnitAddr
		{
			get
			{
				return this._cUnitAddr;
			}
			set
			{
				if ((this._cUnitAddr != value))
				{
					this.OncUnitAddrChanging(value);
					this.SendPropertyChanging();
					this._cUnitAddr = value;
					this.SendPropertyChanged("cUnitAddr");
					this.OncUnitAddrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cUnitZap", DbType="VarChar(6)")]
		public string cUnitZap
		{
			get
			{
				return this._cUnitZap;
			}
			set
			{
				if ((this._cUnitZap != value))
				{
					this.OncUnitZapChanging(value);
					this.SendPropertyChanging();
					this._cUnitZap = value;
					this.SendPropertyChanged("cUnitZap");
					this.OncUnitZapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cUnitTel", DbType="VarChar(30)")]
		public string cUnitTel
		{
			get
			{
				return this._cUnitTel;
			}
			set
			{
				if ((this._cUnitTel != value))
				{
					this.OncUnitTelChanging(value);
					this.SendPropertyChanging();
					this._cUnitTel = value;
					this.SendPropertyChanged("cUnitTel");
					this.OncUnitTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cUnitFax", DbType="VarChar(30)")]
		public string cUnitFax
		{
			get
			{
				return this._cUnitFax;
			}
			set
			{
				if ((this._cUnitFax != value))
				{
					this.OncUnitFaxChanging(value);
					this.SendPropertyChanging();
					this._cUnitFax = value;
					this.SendPropertyChanged("cUnitFax");
					this.OncUnitFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cUnitEMail", DbType="VarChar(40)")]
		public string cUnitEMail
		{
			get
			{
				return this._cUnitEMail;
			}
			set
			{
				if ((this._cUnitEMail != value))
				{
					this.OncUnitEMailChanging(value);
					this.SendPropertyChanging();
					this._cUnitEMail = value;
					this.SendPropertyChanged("cUnitEMail");
					this.OncUnitEMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cUnitTaxNo", DbType="VarChar(20)")]
		public string cUnitTaxNo
		{
			get
			{
				return this._cUnitTaxNo;
			}
			set
			{
				if ((this._cUnitTaxNo != value))
				{
					this.OncUnitTaxNoChanging(value);
					this.SendPropertyChanging();
					this._cUnitTaxNo = value;
					this.SendPropertyChanged("cUnitTaxNo");
					this.OncUnitTaxNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cUnitLP", DbType="VarChar(16)")]
		public string cUnitLP
		{
			get
			{
				return this._cUnitLP;
			}
			set
			{
				if ((this._cUnitLP != value))
				{
					this.OncUnitLPChanging(value);
					this.SendPropertyChanging();
					this._cUnitLP = value;
					this.SendPropertyChanged("cUnitLP");
					this.OncUnitLPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cFinKind", DbType="VarChar(16)")]
		public string cFinKind
		{
			get
			{
				return this._cFinKind;
			}
			set
			{
				if ((this._cFinKind != value))
				{
					this.OncFinKindChanging(value);
					this.SendPropertyChanging();
					this._cFinKind = value;
					this.SendPropertyChanged("cFinKind");
					this.OncFinKindChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cFinType", DbType="VarChar(16)")]
		public string cFinType
		{
			get
			{
				return this._cFinType;
			}
			set
			{
				if ((this._cFinType != value))
				{
					this.OncFinTypeChanging(value);
					this.SendPropertyChanging();
					this._cFinType = value;
					this.SendPropertyChanged("cFinType");
					this.OncFinTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cEntType", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string cEntType
		{
			get
			{
				return this._cEntType;
			}
			set
			{
				if ((this._cEntType != value))
				{
					this.OncEntTypeChanging(value);
					this.SendPropertyChanging();
					this._cEntType = value;
					this.SendPropertyChanged("cEntType");
					this.OncEntTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cTradeKind", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string cTradeKind
		{
			get
			{
				return this._cTradeKind;
			}
			set
			{
				if ((this._cTradeKind != value))
				{
					this.OncTradeKindChanging(value);
					this.SendPropertyChanging();
					this._cTradeKind = value;
					this.SendPropertyChanged("cTradeKind");
					this.OncTradeKindChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UA_Account_UA_Account_sub", Storage="_UA_Account_sub", ThisKey="cAcc_Id", OtherKey="cAcc_Id")]
		public EntitySet<UA_Account_sub> UA_Account_sub
		{
			get
			{
				return this._UA_Account_sub;
			}
			set
			{
				this._UA_Account_sub.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_UA_Account_sub(UA_Account_sub entity)
		{
			this.SendPropertyChanging();
			entity.UA_Account = this;
		}
		
		private void detach_UA_Account_sub(UA_Account_sub entity)
		{
			this.SendPropertyChanging();
			entity.UA_Account = null;
		}
	}
}
#pragma warning restore 1591
