{
    "version":"T31082",
    "connectionString":"Data Source=W7S2K;Initial Catalog=UFSystem;User ID=sa;Password=lckj@666;Encrypt=False;TrustServerCertificate=True",
    "oldYear":"2018",
    "newYear":"2019",
    "account": ["003", "006", "096", "358"],
    "createNewYearDbSentencesQueue": ["restoreDB",
        "AddMemo",
        "DeleteMCs",
        "DeleteInsertFitem",
        "DeleteInsertForeigncurrency",
        "DeleteInsertCode",
        "DeleteInsertDsign",
        "DeleteInsertDsigns",
        "DeleteInsertAccInformation",
        "DeleteInsertBank",
        "DeleteInsertCostObj",
        "DeleteInsertDistrictClass",
        "DeleteInsertCustomerClass",
        "DeleteInsertCustomer",
        "DeleteInsertDepartment",
        "DeleteInsertExpenseItem",
        "DeleteInsertGradeDef",
        "DeleteInsertInventoryClass",
        "DeleteInsertInventory",
        "DeleteInsertWarehouse",
        "DeleteInsertPayCondition",
        "DeleteInsertPerson",
        "DeleteInsertProductStructure",
        "DeleteInsertProductStructures",
        "DeleteInsertRd_Style",
        "DeleteInsertPurchaseType",
        "DeleteInsertSaleType",
        "DeleteInsertSettleStyle",
        "DeleteInsertShippingChoice",
        "DeleteInsertVendorClass",
        "DeleteInsertVendor",
        "DeleteInsertGL_bdigest",
        "DeleteInsertUserDef",
        "DeleteInsertUserDefine",
        "DeleteInsertGL_btext",
        "DeleteInsertGL_mcodeauth",
        "DeleteInsertGL_mcodeused",
        "DeleteInsertGL_mitemused",
        "DeleteInsertap_Midexch",
        "DeleteInsertap_Midexch",
        "DeleteInsertInvoiceItem",
        "DeleteInsertInvoiceItem_",
        "DeleteInsertInvoiceItem_sal",
        "DeleteInsertInvoiceItema",
        "DeleteInsertPrintEx",
        "DeleteInsertPrintDef",
        "DeleteInsertRpt_FldDEF",
        "DeleteInsertRpt_FltDEF",
        "DeleteInsertRpt_Folder",
        "DeleteInsertRpt_GlbDef",
        "DeleteInsertRpt_RelDEF",
        "DeleteInsertVouchers",
        "DeleteInsertVouchFormat",
        "DeleteInsertVouchFormats",
        "DeleteInsertVouchList",
        "DeleteInsertVouchType",
        "DeleteInsertAp_MyTableSet",
        "DeleteInsertAP_DispSet",
        "DeleteInsertAp_InputCode",
        "DeleteInsertAp_SStyleCode",
        "DeleteInsertDep_Auth",
        "DeleteInsertAr_BadAge",
        "DeleteInsertAccessaries",
        "DeleteInsertAp_VouchType",
        "DeleteInsertAp_InvCode",
        "DeleteInsertAp_Lock",
        "DeleteInsertAp_CtrlCode",
        "DeleteInsertfitemgrademode",
        "DeleteInsertfitemstructure",
        "DeleteInsertfitemstrumode",
        "DeleteInsertAp_AlarmSet",
        "DeleteInsertAp_BillAge",
        "DeleteInsertGL_bage",
        "DeleteInsertGL_bautotran",
        "DeleteInsertGL_bfreq",
        "DeleteInsertGL_bmulti",
        "DeleteInsertFA_Departments",
        "DeleteInsertRPT_GrpDef",
        "DeleteInsertRPT_ItmDef",
        "DeleteInsertWareAuth",
        "DeleteInsertPosition",
        "DeleteInsertPersonMSG",
        "DeleteInsertGL_mybooktype",
        "DeleteInsertAp_YWBillAge",
        "DeleteInsertwastage",
        "DeleteInsertT_Rpt_Folder",
        "DeleteInsertT_Rpt_GlbDEF",
        "DeleteInsertT_Rpt_FldDEF",
        "DeleteInsertT_Rpt_FltDEF",
        "DeleteInsertT_Rpt_Property",
        "DeleteInsertAccountPeriod",
        "DeleteInsertBI_NB_Account",
        "DeleteInsertMC_MessageTemplate",
        "DeleteInsertBI_NB_Option",
        "DeleteInsertMC_MessageTemplateAttach",
        "DeleteInsertMC_MessageTemplateToList",
        "DeleteInsertBI_NB_UserAuthority",
        "DeleteInsertBI_NB_VisibleField",
        "DeleteInsertAA_columndic",
        "DeleteInsertAA_columnset",
        "DeleteInsertMC_SendTime",
        "DeleteInsertMC_MyAccount",
        "DeleteInsertWareHouseWarnInfo",
        "DeleteInsertGL_blreq",
        "DeleteInsertufdts_datalog",
        "DeleteInsertufdts_datadel",
        "UpdateWarehouse",
        "DeleteInsertInventory_1",
        "DeleteInsertInventory_2",
        "DeleteInsertInvoiceItem_",
        "DeleteInsertInvoiceItem_Ap",
        "DeleteInsertInvoiceItem_sal",
        "DeleteInsertInvoiceItema",
        "DeleteInsertKCHSItem",
        "DeleteInsertpo",
        "DeleteInsertPS",
        "DeleteInsertInvoiceItem_PRN",
        "DeleteInsertInvoiceItem_ApPRN",
        "DeleteInsertInvoiceItem_salPRN",
        "DeleteInsertInvoiceItemaPRN",
        "DeleteInsertKCHSItemPRN",
        "DeleteInsertpoPRN",
        "DeleteInsertVoucherNumber",
        "DeleteInsertVoucherPrefabricate",
        "DeleteInsertVoucherContrapose",
        "DeleteInsertVoucherHistory",
        "UpdateUA_Period",
        "DeleteInsertUA_HoldAuth",
        "UpdataUA_Account_Sub",
        "Updatagl_mend"
    ],
    "carryForwardGL": [
        "DeleteInsertGL_bmultiGroup",
        "DeleteInsertgl_accsum",
        "DeleteInsertgl_accass",
        "DeleteInsertgl_accvouch",
        "DeleteInsertrp_bankrecp",
        "DeleteInsertrp_cheque",
        "DeleteInsertbi_nb_payment",
        "DeleteInsertTAX_QYSDS_YDSB_A",
        "DeleteInsertTAX_QYSDS_YDSB_B",
        "DeleteInsertTAX_SB_NSSB_NEW_ZB",
        "DeleteInsertTAX_SB_NSSB_NEW_FB1",
        "DeleteInsertTAX_SB_NSSB_NEW_FB1_SWITCH",
        "DeleteInsertTAX_SB_NSSB_NEW_FB2",
        "DeleteInsertTAX_SB_NSSB_NEW_FB2_SWITCH",
        "DeleteInsertTAX_SB_NSSB_NEW_FB3",
        "DeleteInsertTAX_XGM_SH_NEW",
        "DeleteInsertTAX_XGM_SWITCH",
        "DeleteInsertTAX_YYS_CZZB",
        "DeleteInsertTAX_YYS_DM",
        "DeleteInsertTAX_YYS_FB",
        "DeleteInsertTAX_YYS_JCXMHZ",
        "DeleteInsertTAX_YYS_JCXMMX",
        "DeleteInsertTAX_YYS_JR",
        "DeleteInsertTAX_YYS_SHYYSSB",
        "DeleteInsertTAX_YYS_YDJZY",
        "DeleteInsertTAX_YYS_YSYJCXMMX",
        "DeleteInsertTAX_YYS_FB7",
        "DeleteInsertTAX_XFS_YAN_BQDSDJSEJSB",
        "DeleteInsertTAX_XFS_YAN_BQZYKCSEJSB",
        "DeleteInsertTAX_XFS_YAN_JYXSMXB",
        "DeleteInsertTAX_XFS_YAN_ZB",
        "DeleteInsertTAX_XFS_YAN_ZBMX",
        "DeleteInsertTAX_XFS_JIU_BQDSDJSEJSB",
        "DeleteInsertTAX_XFS_JIU_BQZYDJSEJSB",
        "DeleteInsertTAX_XFS_JIU_BQZYDJSEJSB_MX",
        "DeleteInsertTAX_XFS_JIU_SCJYQKB",
        "DeleteInsertTAX_XFS_JIU_ZB",
        "DeleteInsertTAX_XFS_JIU_ZBMX",
        "DeleteInsertTAX_XFS_CPY_BQDSDJSEJSB",
        "DeleteInsertTAX_XFS_CPY_BQDSDJSEJSB",
        "DeleteInsertTAX_XFS_CPY_BQZYKCSEJSB_FB",
        "DeleteInsertTAX_XFS_CPY_BQZYKCSEJSB_MXB",
        "DeleteInsertTAX_XFS_CPY_XSMXB",
        "DeleteInsertTAX_XFS_CPY_ZB",
        "DeleteInsertTAX_XFS_CPY_ZBMX",
        "DeleteInsertTAX_XFS_QTXFP_BQDSDJSEJSB",
        "DeleteInsertTAX_XFS_QTXFP_BQZYKCSEJSB",
        "DeleteInsertTAX_XFS_QTXFP_BQZYKCSEJSB_MXB",
        "DeleteInsertTAX_XFS_QTXFP_SCJYQKB",
        "DeleteInsertTAX_XFS_QTXFP_ZB",
        "DeleteInsertTAX_XFS_QTXFP_ZBMX",
        "DeleteInsertTAX_XFS_XQC_BQDSDJSEJSB",
        "DeleteInsertTAX_XFS_XQC_SCJYQKB",
        "DeleteInsertTAX_XFS_XQC_ZB",
        "DeleteInsertTAX_XFS_XQC_ZBMX",
        "DeleteInsertTAX_SSFX_CWZBFXB",
        "DeleteInsertTAX_TaxWarning_Qysds",
        "DeleteInsertTAX_TaxWarning_Sfl",
        "DeleteInsertTAX_ZDJSZBB",
        "DeleteInsertTAX_ObtainFinancia_Instance",
        "DeleteInsertTAX_NSRXX",
        "DeleteInsertTAX_SZXM",
        "DeleteInsertTAX_YJSZ"
    ],
    "carryForwardFA": [
        "DeleteInsertAccInformation",
        "DeleteInsertfa_AssetAttached",
        "DeleteInsertfa_AssetTypes",
        "DeleteInsertfa_Depreciations",
        "DeleteInsertfa_Origins",
        "DeleteInsertfa_Status",
        "DeleteInsertfa_Items",
        "DeleteInsertCREATEUNIQUEfa_ItemsManual",
        "DeleteInsertfa_ItemsOfModel",
        "DeleteInsertfa_ItemsOfQuery",
        "DeleteInsertfa_Models",
        "DeleteInsertfa_Cards",
        "DeleteInsertfa_CardsSheets",
        "DeleteInsertfa_Control",
        "Deletefa_DeprList",
        "DeleteInsertfa_DeprTransactions",
        "DeleteInsertfa_DeprVoucherMain",
        "DeleteInsertfa_DeprVouchers",
        "DeleteInsertfa_DeprVouchers_pre",
        "DeleteInsertfa_Dictionary",
        "DeleteInsertfa_EvaluateMain",
        "DeleteInsertfa_EvaluateVouchers",
        "DeleteInsertfa_Objects",
        "DeleteInsertfa_QueryFilters",
        "DeleteInsertfa_Querys",
        "DeleteInsertfa_Total",
        "DeleteInsertfa_Vouchers",
        "DeleteInsertfa_WorkLoad",
        "DeleteInsertfa_ZWVouchers",
        "DeleteInsertfa_JKItemSet",
        "DeleteInsertfa_JKSet",
        "DeleteInsertfa_VtsObject",
        "UPDATEAccInformation",
        "UPDATEfa_DeprTransactions1",
        "UPDATEfa_DeprTransactions2",
        "UPDATEfa_DeprTransactions3",
        "UPDATEfa_DeprTransactions4",
        "UPDATEfa_WorkLoad",
        "DeleteInsertfa_DeprVoucherMain",
        "DeleteInsertfa_DeprVouchers",
        "DeleteInsertfa_Control",
        "DeleteUPDATEfa_Total",
        "UPDATEfa_EvaluateMainfa_EvaluateVouchersfa_Cardsfa_JKSet"
    ],
    "carryForwardWA": [
            "DeleteInsertWA_account",
            "Insert WA_Authority",
            "Alter WA_BankName",
            "Delete WA_Bank,WA_Bank_set,WA_BankPar,WA_BankTop,WA_BankName",
            "Insert WA_BankName",
            "Delete wa_psn,WA_Grade",
            "Insert WA_Grade",
            "Delete WA_GZItem,WA_GZtblSet",
            "Insert WA_GZtblSet",
            "Insert WA_GZItem",
            "Insert WA_Dept",
            "Delete,Insert WA_PsnMsg",
            "Alter,Insert WA_Psn",
            "Alter,Insert WA_Bank",
            "Insert WA_Bank_Set",
            "Insert WA_BankPar",
            "Insert WA_BankTop",
            "Insert WA_FilterExpList",
            "Delete,Insert WA_FilterName",
            "Insert WA_Formula",
            "Insert WA_FT_Sum",
            "Insert WA_FTName",
            "Insert WA_GZsumComCfg",
            "Insert WA_FTInfo",
            "Insert WA_FTDept",
            "DeleteInsertWA_GZBNameWA_GZBItemDept",
            "Insert WA_GZBItemGrd",
            "Insert WA_GZBItemTitle",
            "Insert WA_tblRCsetP",
            "Insert WA_tblRCsetM",
            "Insert,Update WA_GZData",
            "ALTER WA_GZHZB",
            "Insert WA_SDS_p",
            "Insert WA_SDS_SL",
            "Insert WA_SelectMoney",
            "Insert WA_JKSet",
            "Insert WA_JKItemSet",
            "Insert WA_RatePayItems",
            "Insert WA_State",
            "Update WA_account",
            "DELETE WA_GZData",
            "UPDATE GL_mend",
            "UPDATE OldYear WA_account"
        ]
}